import { useRef, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft, BellRing, CheckCircle2, Download, FileArchive, FileOutput, FileSearch, FolderPlus, Loader2, Mail, Play, Plus, Search, Send, Slack, Sparkles, ToggleLeft, ToggleRight, UploadCloud } from "lucide-react";

function prettyDate(value: Date | string | null | undefined) { return value ? new Date(value).toLocaleString(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }) : "—"; }
function formatBytes(bytes: number) { return bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }

export default function TestingConsole() {
  const fileRef = useRef<HTMLInputElement>(null);
  const [sourceFile, setSourceFile] = useState<File | null>(null);
  const [extracting, setExtracting] = useState(false);
  const [search, setSearch] = useState("");
  const [collectionName, setCollectionName] = useState("");
  const [selectedCollection, setSelectedCollection] = useState<number | undefined>();
  const [alertName, setAlertName] = useState("Revenue growth watch");
  const [alertQuery, setAlertQuery] = useState("revenue growth");
  const [alertChannel, setAlertChannel] = useState<"in_app" | "email" | "slack">("in_app");
  const [destination, setDestination] = useState("analyst@example.com");
  const [selectedReportId, setSelectedReportId] = useState<number | undefined>();
  const [deliveryChannel, setDeliveryChannel] = useState<"email" | "slack">("email");

  const utils = trpc.useUtils();
  const reports = trpc.reports.list.useQuery();
  const searchResults = trpc.reports.search.useQuery({ query: search }, { enabled: search.trim().length > 0 });
  const collections = trpc.reports.collections.list.useQuery();
  const alerts = trpc.reports.alerts.list.useQuery();
  const deliveries = trpc.reports.deliveries.useQuery();
  const activeReportId = selectedReportId || reports.data?.[0]?.id;
  const summarize = trpc.reports.summarize.useMutation({ onSuccess: async (report) => { await utils.reports.list.invalidate(); setExtracting(false); setSourceFile(null); setSelectedReportId(report.id); toast.success("Extraction complete", { description: `${report.fileName} was parsed and summarized.` }); }, onError: (error) => { setExtracting(false); toast.error("Extraction failed", { description: error.message }); } });
  const createCollection = trpc.reports.collections.create.useMutation({ onSuccess: async () => { setCollectionName(""); await utils.reports.collections.list.invalidate(); toast.success("Collection created"); } });
  const addToCollection = trpc.reports.collections.addReport.useMutation({ onSuccess: () => toast.success("Report added to collection") });
  const createAlert = trpc.reports.alerts.create.useMutation({ onSuccess: async () => { await utils.reports.alerts.list.invalidate(); toast.success("Alert saved"); } });
  const toggleAlert = trpc.reports.alerts.toggle.useMutation({ onSuccess: async () => { await utils.reports.alerts.list.invalidate(); } });
  const deliver = trpc.reports.deliver.useMutation({ onSuccess: async (result) => { await utils.reports.deliveries.invalidate(); toast.success(`${result.channel === "email" ? "Email" : "Slack"} delivery simulated`, { description: "No external message was sent." }); } });
  const exportPdf = trpc.reports.exportPdf.useMutation({ onSuccess: (result) => { const link = document.createElement("a"); link.href = `data:application/pdf;base64,${result.dataBase64}`; link.download = result.fileName; link.click(); toast.success("PDF downloaded"); } });

  const startExtraction = async (file: File) => {
    setSourceFile(file); setExtracting(true);
    try {
      const dataUrl = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result || "")); reader.onerror = () => reject(new Error("File could not be read")); reader.readAsDataURL(file); });
      summarize.mutate({ fileName: file.name, mimeType: file.type || "application/octet-stream", fileSize: file.size, fileData: dataUrl, sourceText: "" });
    } catch { setExtracting(false); toast.error("Could not read file"); }
  };

  return <div className="min-h-screen bg-[#f4f7f4] text-[#14201d]"><header className="sticky top-0 z-20 border-b border-[#dfe9e1] bg-[#f8faf8]/95 backdrop-blur-md"><div className="mx-auto flex h-[70px] max-w-[1240px] items-center justify-between px-5 sm:px-8"><Link href="/" className="flex items-center gap-2.5 text-[#10483f]"><div className="flex h-8 w-8 items-center justify-center rounded-[10px] bg-[#10483f] text-[#dcf7df]"><Sparkles className="h-4 w-4" /></div><span className="font-display text-[16px] font-extrabold tracking-[-0.04em]">FinBrief</span></Link><Link href="/"><Button variant="outline" className="h-9 border-[#d8e5db] bg-white text-[11px] font-bold text-[#4c6b5d]"><ArrowLeft className="mr-1.5 h-3.5 w-3.5" /> Back to overview</Button></Link></div></header>
    <main className="mx-auto max-w-[1240px] px-5 py-7 sm:px-8 lg:py-10"><div className="mb-8"><div className="mb-2 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#5c8b78]"><Play className="h-3 w-3" /> QA workspace</div><h1 className="font-display text-[30px] font-extrabold tracking-[-0.05em] text-[#173e34] sm:text-[38px]">Test the full FinBrief workflow.</h1><p className="mt-2 max-w-[700px] text-[14px] leading-[1.6] text-[#718178]">Native extraction, library organization, alert rules, PDF export, and simulated delivery are all wired below. Use a real report or a small test document to exercise each path.</p></div>
      <section className="mb-5 grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><Card className="border-0 bg-white paper-shadow"><CardHeader className="flex flex-row items-start justify-between px-6 pb-3 pt-6"><div><CardTitle className="font-display text-[16px] font-extrabold text-[#244e42]">1. Native extraction test</CardTitle><p className="mt-1 text-[12px] text-[#87968e]">PDF and DOCX parsing happens server-side before AI summarization.</p></div><div className="rounded-lg bg-[#e7f3e9] p-2 text-[#43846d]"><FileSearch className="h-4 w-4" /></div></CardHeader><CardContent className="px-6 pb-6"><input ref={fileRef} type="file" className="hidden" accept=".pdf,.docx,.txt,.csv,.md" onChange={(event) => { const file = event.target.files?.[0]; if (file) void startExtraction(file); event.currentTarget.value = ""; }} /><button onClick={() => fileRef.current?.click()} className="flex w-full flex-col items-center justify-center rounded-[13px] border border-dashed border-[#c9dcd0] bg-[#f7fbf7] px-5 py-8 text-center transition-colors hover:border-[#73ac8d] hover:bg-[#f0f8f1]">{extracting ? <Loader2 className="mb-3 h-6 w-6 animate-spin text-[#43846d]" /> : <UploadCloud className="mb-3 h-6 w-6 text-[#43846d]" />}<div className="text-[13px] font-bold text-[#315e4e]">{extracting ? `Parsing ${sourceFile?.name}…` : "Choose a PDF, DOCX, TXT, CSV, or Markdown file"}</div><div className="mt-1 text-[11px] text-[#8a9b91]">{sourceFile && !extracting ? `${sourceFile.name} · ${formatBytes(sourceFile.size)}` : "Up to 20 MB"}</div></button><div className="mt-4 flex items-start gap-2 rounded-[10px] bg-[#eef7ef] p-3 text-[11px] leading-[1.5] text-[#668676]"><CheckCircle2 className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[#58a17a]" />For PDFs and DOCX files, the browser sends bytes to the backend and the backend extracts text using native parsers. No external conversion service is required.</div></CardContent></Card>
        <Card className="border-0 bg-[#10483f] text-white shadow-[0_16px_36px_rgba(16,72,63,.16)]"><CardContent className="p-6"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.15em] text-[#a8d2b4]"><FileOutput className="h-3.5 w-3.5" /> Testing checklist</div><div className="mt-5 space-y-3">{["Upload a native PDF or DOCX", "Search it by company or headline", "Save it to a collection", "Create an alert rule", "Export the AI brief as PDF", "Simulate email or Slack delivery"].map((item, index) => <div key={item} className="flex items-center gap-3 text-[12px] text-[#d8f0dc]"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-[#2c6b5b] text-[10px] font-bold text-[#bcecc5]">{index + 1}</span>{item}</div>)}</div><div className="mt-6 border-t border-[#36725f] pt-4 text-[11px] leading-[1.5] text-[#9dc6ae]">Email and Slack are in <strong className="text-[#c5ebcd]">simulation mode</strong> for testing. Each action is logged in the delivery history below.</div></CardContent></Card></section>

      <section className="mb-5 grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><Card className="border-0 bg-white soft-shadow"><CardHeader className="flex flex-row items-center justify-between px-6 pb-3 pt-6"><div><CardTitle className="font-display text-[16px] font-extrabold text-[#244e42]">2. Search reports</CardTitle><p className="mt-1 text-[12px] text-[#87968e]">Search company, file name, headline, and summary.</p></div><Search className="h-4 w-4 text-[#5b9b79]" /></CardHeader><CardContent className="px-6 pb-6"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#97aaa0]" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Try: revenue, margin, Northstar" className="h-10 w-full rounded-[10px] border border-[#d9e7dc] bg-[#f8fbf8] pl-9 pr-3 text-[12px] outline-none ring-[#8bc49b] focus:ring-2" /></div><div className="mt-4 space-y-2">{search ? (searchResults.data?.length ? searchResults.data.map((report) => <Link key={report.id} href={`/reports/${report.id}`} className="flex items-center justify-between rounded-lg bg-[#f5faf5] px-3 py-2.5 hover:bg-[#eaf5eb]"><span className="truncate text-[12px] font-bold text-[#3b6757]">{report.company || report.fileName}</span><span className="ml-3 text-[10px] text-[#88a095]">{report.period || "—"}</span></Link>) : <div className="py-4 text-center text-[11px] text-[#98a79f]">No matching reports yet.</div>) : <div className="py-4 text-center text-[11px] text-[#98a79f]">Start typing to search your library.</div>}</div></CardContent></Card>
        <Card className="border-0 bg-white soft-shadow"><CardHeader className="flex flex-row items-center justify-between px-6 pb-3 pt-6"><div><CardTitle className="font-display text-[16px] font-extrabold text-[#244e42]">3. Collections</CardTitle><p className="mt-1 text-[12px] text-[#87968e]">Group reports by watchlist, sector, or deal team.</p></div><FolderPlus className="h-4 w-4 text-[#5b9b79]" /></CardHeader><CardContent className="px-6 pb-6"><div className="flex gap-2"><input value={collectionName} onChange={(event) => setCollectionName(event.target.value)} placeholder="New collection name" className="h-10 min-w-0 flex-1 rounded-[10px] border border-[#d9e7dc] bg-[#f8fbf8] px-3 text-[12px] outline-none focus:ring-2 focus:ring-[#8bc49b]" /><Button disabled={!collectionName.trim() || createCollection.isPending} onClick={() => createCollection.mutate({ name: collectionName.trim(), description: "Created from QA console", color: "sage" })} className="h-10 bg-[#10483f] text-[11px] font-bold"><Plus className="mr-1 h-3.5 w-3.5" /> Create</Button></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{collections.data?.length ? collections.data.map((collection) => <button key={collection.id} onClick={() => setSelectedCollection(collection.id)} className={`rounded-[10px] border px-3 py-2.5 text-left ${selectedCollection === collection.id ? "border-[#82bd98] bg-[#edf8ee]" : "border-[#e2ece3] bg-[#fbfdfb]"}`}><div className="text-[12px] font-bold text-[#3b6757]">{collection.name}</div><div className="mt-0.5 text-[10px] text-[#91a098]">{selectedCollection === collection.id ? "Selected" : "Click to select"}</div></button>) : <div className="col-span-2 py-3 text-[11px] text-[#98a79f]">Create your first collection above.</div>}</div><Button disabled={!selectedCollection || !activeReportId || addToCollection.isPending} onClick={() => selectedCollection && activeReportId && addToCollection.mutate({ collectionId: selectedCollection, reportId: activeReportId })} variant="outline" className="mt-4 h-9 w-full border-[#d7e6da] text-[11px] font-bold text-[#4d7864]"><FolderPlus className="mr-1.5 h-3.5 w-3.5" /> Add selected report to collection</Button></CardContent></Card></section>

      <section className="mb-5 grid gap-5 lg:grid-cols-[1fr_1fr]"><Card className="border-0 bg-white soft-shadow"><CardHeader className="flex flex-row items-center justify-between px-6 pb-3 pt-6"><div><CardTitle className="font-display text-[16px] font-extrabold text-[#244e42]">4. Saved alerts</CardTitle><p className="mt-1 text-[12px] text-[#87968e]">Store rules for future report monitoring.</p></div><BellRing className="h-4 w-4 text-[#c18c3e]" /></CardHeader><CardContent className="px-6 pb-6"><div className="grid gap-2 sm:grid-cols-2"><input value={alertName} onChange={(event) => setAlertName(event.target.value)} placeholder="Alert name" className="h-9 rounded-[9px] border border-[#d9e7dc] bg-[#f8fbf8] px-3 text-[11px] outline-none focus:ring-2 focus:ring-[#8bc49b]" /><input value={alertQuery} onChange={(event) => setAlertQuery(event.target.value)} placeholder="Keyword or company" className="h-9 rounded-[9px] border border-[#d9e7dc] bg-[#f8fbf8] px-3 text-[11px] outline-none focus:ring-2 focus:ring-[#8bc49b]" /></div><div className="mt-2 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><select value={alertChannel} onChange={(event) => setAlertChannel(event.target.value as typeof alertChannel)} className="h-9 rounded-[9px] border border-[#d9e7dc] bg-[#f8fbf8] px-3 text-[11px] text-[#557266] outline-none"><option value="in_app">In-app</option><option value="email">Email</option><option value="slack">Slack</option></select><select className="h-9 rounded-[9px] border border-[#d9e7dc] bg-[#f8fbf8] px-3 text-[11px] text-[#557266] outline-none"><option>Instant</option><option>Daily</option><option>Weekly</option></select><Button disabled={createAlert.isPending} onClick={() => createAlert.mutate({ name: alertName, query: alertQuery, channel: alertChannel, destination: alertChannel === "in_app" ? undefined : destination, frequency: "instant" })} className="h-9 bg-[#10483f] text-[11px] font-bold"><BellRing className="mr-1 h-3.5 w-3.5" /> Save</Button></div><div className="mt-4 space-y-2">{alerts.data?.length ? alerts.data.slice(0, 3).map((alert) => <div key={alert.id} className="flex items-center gap-2 rounded-[9px] bg-[#f8fbf8] px-3 py-2.5"><div className="min-w-0 flex-1"><div className="truncate text-[11px] font-bold text-[#456b5b]">{alert.name}</div><div className="mt-0.5 truncate text-[10px] text-[#91a098]">{alert.query} · {alert.channel}</div></div><button onClick={() => toggleAlert.mutate({ id: alert.id, enabled: alert.enabled === 0 })} className="text-[#5b9b79]" aria-label="Toggle alert">{alert.enabled ? <ToggleRight className="h-5 w-5" /> : <ToggleLeft className="h-5 w-5 text-[#a7b5ac]" />}</button></div>) : <div className="py-3 text-[11px] text-[#98a79f]">No saved alerts yet.</div>}</div></CardContent></Card>

        <Card className="border-0 bg-white soft-shadow"><CardHeader className="flex flex-row items-center justify-between px-6 pb-3 pt-6"><div><CardTitle className="font-display text-[16px] font-extrabold text-[#244e42]">5. Export & delivery</CardTitle><p className="mt-1 text-[12px] text-[#87968e]">Download a PDF or log a simulated email/Slack send.</p></div><Send className="h-4 w-4 text-[#5b9b79]" /></CardHeader><CardContent className="px-6 pb-6"><div className="flex gap-2"><select value={activeReportId || ""} onChange={(event) => setSelectedReportId(Number(event.target.value))} className="h-9 min-w-0 flex-1 rounded-[9px] border border-[#d9e7dc] bg-[#f8fbf8] px-3 text-[11px] text-[#557266] outline-none"><option value="">Select a report</option>{reports.data?.map((report) => <option key={report.id} value={report.id}>{report.company || report.fileName}</option>)}</select><Button disabled={!activeReportId || exportPdf.isPending} onClick={() => activeReportId && exportPdf.mutate({ id: activeReportId })} variant="outline" className="h-9 border-[#d7e6da] text-[11px] font-bold text-[#4d7864]"><Download className="mr-1 h-3.5 w-3.5" /> PDF</Button></div><div className="mt-2 flex gap-2"><input value={destination} onChange={(event) => setDestination(event.target.value)} placeholder="email@example.com or #channel" className="h-9 min-w-0 flex-1 rounded-[9px] border border-[#d9e7dc] bg-[#f8fbf8] px-3 text-[11px] outline-none focus:ring-2 focus:ring-[#8bc49b]" /><select value={deliveryChannel} onChange={(event) => setDeliveryChannel(event.target.value as typeof deliveryChannel)} className="h-9 rounded-[9px] border border-[#d9e7dc] bg-[#f8fbf8] px-2 text-[11px] text-[#557266] outline-none"><option value="email">Email</option><option value="slack">Slack</option></select><Button disabled={!activeReportId || !destination || deliver.isPending} onClick={() => activeReportId && deliver.mutate({ reportId: activeReportId, channel: deliveryChannel, destination })} className="h-9 bg-[#10483f] text-[11px] font-bold"><Send className="mr-1 h-3.5 w-3.5" /> Send</Button></div><div className="mt-3 flex gap-3 text-[10px] text-[#91a098]"><span className="flex items-center gap-1"><Mail className="h-3 w-3" /> Email simulation</span><span className="flex items-center gap-1"><Slack className="h-3 w-3" /> Slack simulation</span></div><div className="mt-4 border-t border-[#edf2ed] pt-3">{deliveries.data?.length ? deliveries.data.slice(0, 3).map((item) => <div key={item.id} className="flex items-center gap-2 py-1.5 text-[10px]"><Badge className="border-0 bg-[#e5f3e7] text-[9px] font-bold text-[#3f8465]">SIMULATED</Badge><span className="text-[#678074]">{item.channel} → {item.destination}</span><span className="ml-auto text-[#a0aea5]">{prettyDate(item.createdAt)}</span></div>) : <div className="text-[11px] text-[#98a79f]">Delivery activity will appear here.</div>}</div></CardContent></Card></section>
      <div className="flex items-center gap-2 rounded-[12px] border border-[#e0e9e1] bg-white/70 px-4 py-3 text-[11px] text-[#799084]"><FileArchive className="h-4 w-4 text-[#70a184]" />Test data stays scoped to this workspace. External email and Slack providers are intentionally not contacted in simulation mode.</div>
    </main></div>;
}
